[package]
name = "one-do-three"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes = "0.7.5"
block-modes = "0.8.1"
hex-literal = "0.3.4"
rand = "0.8"